version: 2.1

orbs:
  docker: circleci/docker@2.0.1

jobs:
  build-docker-image:
    machine:
        image: ubuntu-1604:202004-01
    steps:
        - checkout
        - docker/check:
            docker-username: DOCKERHUB_LOGIN
            docker-password: DOCKERHUB_PASSWORD
        - docker/build:
            dockerfile: ubuntu-20.04/base/Dockerfile
            image: cristiancmello/ubuntu
            tag: latest
            registry: $DOCKER_REGISTRY
        - docker/publish:
            image: cristiancmello/ubuntu
            tag: latest
            registry: $DOCKER_REGISTRY

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-docker-image:
          context: docker-hub
      # - deploy-docker-image:
      #     machine:
      #         image: ubuntu-1604:202004-01
      #     steps:
      #         - attach_workspace:
      #               at: .
      #         - run:
      #               name: Setup __BUILD_VERSION envvar
      #               command: |
      #                   echo "export __BUILD_VERSION=\"$(cat version.txt)\"" >> $BASH_ENV
      #         - docker/check:
      #               registry: $DOCKER_REGISTRY
      #         - docker/pull:
      #               images: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$__BUILD_VERSION
      #         - run:
      #               name: Tag the image as latest
      #               command: docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$__BUILD_VERSION $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
      #         - docker/push:
      #               image: $DOCKER_IMAGE_NAME
      #               tag: latest
      #               registry: $DOCKER_REGISTRY