version: 2.1

jobs:
  build-deploy:
    machine: true
    steps:
        - checkout
        - run: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_LOGIN --password-stdin
        - run: |
            docker build -t cristiancmello/ubuntu:20.04-base ./ubuntu-20.04/base
        - run: |
            docker push cristiancmello/ubuntu:20.04-base

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: docker-hub