version: 2.1

jobs:
  build:
    machine: true
    steps:
        - checkout
        - run: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_LOGIN --password-stdin
        - run: |
            docker build -t cristiancmello/ubuntu:latest ./ubuntu-20.04/base/Dockerfile

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker-hub
      # - deploy-docker-image:
      #     machine:
      #         image: ubuntu-1604:202004-01
      #     steps:
      #         - attach_workspace:
      #               at: .
      #         - run:
      #               name: Setup __BUILD_VERSION envvar
      #               command: |
      #                   echo "export __BUILD_VERSION=\"$(cat version.txt)\"" >> $BASH_ENV
      #         - docker/check:
      #               registry: $DOCKER_REGISTRY
      #         - docker/pull:
      #               images: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$__BUILD_VERSION
      #         - run:
      #               name: Tag the image as latest
      #               command: docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$__BUILD_VERSION $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
      #         - docker/push:
      #               image: $DOCKER_IMAGE_NAME
      #               tag: latest
      #               registry: $DOCKER_REGISTRY